project 'ExampleSwiftApp-iOS.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'ExampleSwiftApp-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'WebViewJavascriptBridge_WebKit', :path => '../..'

  target 'ExampleSwiftApp-iOSTests' do
    inherit! :search_paths

	pod 'WebViewJavascriptBridge_WebKit', :path => '../..'
  end

end
